feat: 게임 미션
cowaine/is-my-code-that-strange pull request #131
Opened 2024-08-04 00:46 UTC by 0sunset0

소켓 프로그래밍에 익숙하지 않아 게임 캐릭터 데이터 클래스만 설계했습니다..!

2024-08-10 11:01 UTC, corock requested changes
도서 내용 정리와 스터디 질의응답 및 PR, 그리고 미션까지 구현하시느라 수고 많으셨습니다~ 🥇

2024-08-11 14:59 UTC, corock approved these changes

2024-08-11 16:52 UTC, 0sunset0 commented on sunset0/src/main/java/com/cowaine/sunset0/mission/game/character/hero/Hero.java
> +    }
그러네요..ㅎㅎ 이때 뇌가 정지 됐었나봐요

2024-08-11 16:58 UTC, 0sunset0 commented on sunset0/src/main/java/com/cowaine/sunset0/mission/game/character/monster/Slim.java
> +    }
1. createXxx는 하위 타입 클래스를 만들어 반환할 때 쓰면 좋을 것 같고, create는 깔끔해서 좋네요!
2. 개인적으로 데이터를 갖추고 인스턴스화하는 게 좋다고 생각합니다. 객체 생성 비용이 크다면 최대한 생성을 지연시키는 게 좋고, 빈 인스턴스가 잘못 사용 될 수도 있으니까요!

2024-08-11 17:01 UTC, 0sunset0 commented on sunset0/src/main/java/com/cowaine/sunset0/mission/game/character/Health.java
> +    }
체력은 값 객체라고 생각해서 재정의 했습니다. 
용사와 몬스터의 체력을 비교할 일이 생긴다면 `==` 비교를 할 수 있게요..!!

2024-08-13 02:52 UTC, 0sunset0 commented on sunset0/src/main/java/com/cowaine/sunset0/mission/game/character/Level.java
> +    private final int value;
레벨은 특정한 숫자가 자주 쓰여서 싱글톤을 사용하면 어떨까? 싶었고
일련된 숫자들이 쓰일 것 같아서 enum을 사용했습니다!

2024-08-13 03:03 UTC, 0sunset0 commented on sunset0/src/main/java/com/cowaine/sunset0/mission/game/character/monster/Dragon.java
> +        if (is10Percent()) {
`isBreathCase()` 라는 이름으로 변경하고, 확률을 상수화 했습니다!!

2024-09-15 15:51 UTC, corock commented on sunset0/src/main/java/com/cowaine/sunset0/mission/game/character/Level.java
> +    private final int value;
싱글톤 구현 방법은 여러 가지가 있고, `enum` 역시 이펙티브 자바에서 추천한 방식 중 하나이긴 합니다.
하지만 `Level` 은 열거형으로 설계하기보다 [지연 로드 싱글톤 방식](https://en.wikipedia.org/wiki/Initialization-on-demand_holder_idiom)으로 설계해 보는 걸 추천해 드립니다~

2024-09-16 03:37 UTC, corock commented on sunset0/src/main/java/com/cowaine/sunset0/mission/game/character/Health.java
> +    }
동일성을 고려한 점은 매우 좋았습니다! 다만, 지금 재정의한 구현은 `super` 타입인 `Object` 클래스의 기본 구현만 되어 있어요.
이렇게 하면 동일성을 보장한다고 보기 어렵습니다. 실제로 테스트를 해보면 아래와 같은 결과가 나옵니다.

![health-unit-testing](https://github.com/user-attachments/assets/e7da4ba3-8b65-4141-a5bf-f031fcf7581f)

최소한 IntelliJ IDEA 에서 제시하는 템플릿을 사용하거나, _lombok_ 에서 제공하는 `@EqualsAndHashCode` 사용을 추천해 드려요.
두 가지 방법은 모두 `amount` 필드를 `equals` 재정의 시 동등성의 대상으로 포함해서 비교할 수 있습니다.

| 템플릿 사용 | `amount` 필드 포함 |
|--|--|
|  ![equals-and-hash-template](https://github.com/user-attachments/assets/908165f4-d55c-48ab-917d-66354d1702e8) | ![field-to-be-included-in-equals](https://github.com/user-attachments/assets/0b025f2f-7c77-47ff-b47e-153162f583ed) |

그리고 실패했던 테스트 코드 역시 통과합니다.

![tests-are-green](https://github.com/user-attachments/assets/ef8367c0-fecc-47e4-8ca5-a54514328ee2)

2024-09-18 06:39 UTC, merged

2024-09-19 11:59 UTC, 0sunset0 commented on sunset0/src/main/java/com/cowaine/sunset0/mission/game/character/monster/Orc.java
> +    private static int INITIAL_ATTACK_POWER = 6;
(좀 늦었지만)
저는 체력과 공격력은 클래스로 했는데
초기 체력과 초기 공격력도 각각 클래스 설계하라는 말씀이실까요..??

2024-09-19 12:42 UTC, 0sunset0 commented on sunset0/src/main/java/com/cowaine/sunset0/mission/game/character/Health.java
> +    }
분명 이펙티브 자바를 읽었는데 제가 왜 재정의를 저렇게 했는지...ㅎㅎ 
클래스의 필드가 추가된다면 `equals` `hashcode`를 또 다시 재정의 해야 하기 때문에 롬복을 사용하는 걸로 변경했습니다.
테스트 코드와 너무 너무 깔끔한 설명 감사합니다!!

늦었지만 제훈님께 리뷰를 받게 되어 영광이었습니다 스터디 당시 열심히 임하지 못한 것 같아 아쉽고 죄송스러운 마음도 있네요 🥲
매번 공지나 리뷰에서 코드블럭, 강조 등 신경 써주셔서 문서화를 잘하면 보는 입장에서 이렇게 좋구나~를 느꼈습니다
이걸 보실지는 모르겠지만... 주저리 주저리 말해봅니다