feat: 게임 클래스 도메인 설계 1차 완료
cowaine/is-my-code-that-strange pull request #133
Opened 2024-08-09 06:35 UTC by Irisation23

2024-08-10 14:16 UTC, corock requested changes
책 내용 정리와 스터디 질의응답 및 PR, 미션까지 구현하시느라 수고 많으셨습니다~ 🏅

2024-08-10 14:16 UTC, corock commented on irisation23/src/main/java/com/cowaine/irisation23/mission/game/domain/subject/Hero.java
> +    }
아무 행동이 없다면 `action` 필드를 `null` 로 정의하신 것으로 보입니다.
만약 그렇다면 `null` 로 정의하기보단 `action` 필드는 불변으로 만들고, 빈 컬렉션으로 검증하는 방법은 어떨까요?

2024-08-11 09:03 UTC, JoisFe reviewed
고생많으셨습니다 .

2024-08-11 09:03 UTC, JoisFe commented on irisation23/src/main/java/com/cowaine/irisation23/mission/game/domain/subject/GameCharacter.java
> +    final Level level;
단순히 level 필드를 Integer 같은 타입이 아닌
새로운 클래스로 두면서 얻는 장점이 무엇일까요?

2024-08-11 09:03 UTC, JoisFe commented on irisation23/src/main/java/com/cowaine/irisation23/mission/game/domain/subject/Hero.java
> +        return new Hero(id,
Builder를 사용하고 있다면 해당 부분도 Builder를 이용할 수 있는 것 같습니다!
builder를 쓰지 않은 다른 사유가 있을까요?

2024-08-11 09:05 UTC, JoisFe commented on irisation23/src/main/java/com/cowaine/irisation23/mission/game/domain/subject/Dragon.java
> +    private Action<Dragon, Hero> action;
action field 에는 final을 붙여서 불변을 강요하지 않은 이유가 있을까요?

2024-08-11 09:06 UTC, JoisFe commented on irisation23/src/main/java/com/cowaine/irisation23/mission/game/domain/subject/GameCharacter.java
> +public class GameCharacter {
Java 11 을 사용 중이신 걸로 아는데, Java 14 이상을 사용하신다면 Record 를 사용해보는 것도 좋을 것 같습니다.!

2024-08-11 09:08 UTC, JoisFe commented on irisation23/src/main/java/com/cowaine/irisation23/mission/game/server/GameServerShell.java
> +    public static void main(String[] args) throws IOException {
메인 메서드에서 IOException 을 throw 하는 것으로 보이는데 
해당 게임을 진행하면서 발생하는 예외 또한 핸들링하고, 유저에게 문제사항을 알릴 수 있도록 
추가하면 더 완벽한 게임이 될 것 같아요!!

2024-08-11 09:19 UTC, JoisFe commented on irisation23/src/main/java/com/cowaine/irisation23/mission/game/client/GameClient.java
> +            Socket socket = new Socket(serverHost, port);
<img width="549" alt="image" src="https://github.com/user-attachments/assets/3393a897-67f1-4c5d-a63f-efe74252b052">

Socket 경우 Closable을 구현하고 있는데 

try with resource를 사용하는 것은 어떨까요?

2024-08-11 09:45 UTC, JoisFe commented on irisation23/src/main/java/com/cowaine/irisation23/mission/game/domain/behavior/Action.java
> +public interface Action<E extends GameCharacter, T extends GameCharacter> {
`subject` package에 있는 객체들의 행위를
`behavior` package에 모아놓은 것 으로 보입니다.

행위를 클래스화 시킴으로써 어떠한 장점을 얻을 수 있을까요? (전략 패턴과 같은 여러 장점??)

2024-08-11 09:56 UTC, JoisFe commented on irisation23/src/main/java/com/cowaine/irisation23/mission/game/domain/subject/Monster.java
> +public abstract class Monster extends GameCharacter implements ChangAbleState<Monster> {
Monster의 구현체인

Orc, Slime 등

```
@Override
    public Slime changeLevel(Level level) {
        return this.toBuilder()
                   .level(level)
                   .build();
    }

    @Override
    public Slime changeHp(Hp hp) {
        return this.toBuilder()
                   .hp(hp)
                   .build();
    }

    @Override
    public Slime changeAttackPower(AttackPower power) {
        return this.toBuilder()
                   .attackPower(power)
                   .build();
    }
    
  ```
  
위 메서드들을 똑같은 구현을 하고 있는데 그럼 해당 메서드의 구현을 Monster에서 하는게 좋지 않나요?

2024-08-12 11:08 UTC, Irisation23 commented on irisation23/src/main/java/com/cowaine/irisation23/mission/game/client/ClientSession.java
> +        loggingCurrentClientCount();
Console API가 명시된 레포들은 대부분다 `private` 처리되어 있어서 `readLine()`의 동작원리를 볼 수 없네요 ㅠㅠ
해당 어플리케이션 같은 경우는 실제로 출력하는 결과에 집중하지는 못해서 다음번에 기회가 된다면 비즈니스 로직을 분리할 수 있도록 하겠습니다!

2024-08-12 11:12 UTC, Irisation23 commented on irisation23/src/main/java/com/cowaine/irisation23/mission/game/domain/subject/Orc.java
> +    }
넵 완료했습니다.

2024-08-12 11:14 UTC, Irisation23 commented on irisation23/src/main/java/com/cowaine/irisation23/mission/game/domain/behavior/ChangAbleState.java
> +public interface ChangAbleState<T extends GameCharacter> {
<img width="392" alt="image" src="https://github.com/user-attachments/assets/910ac6f6-537a-4888-85c0-ebf4f9e916ca">

해당 고민을 해봤던 경험이 있어서 바꿔보면 이렇게... 되어있어서 부득이하게 `Able` 했답니다..

2024-08-12 12:03 UTC, JoisFe commented on irisation23/src/main/java/com/cowaine/irisation23/mission/game/domain/behavior/ChangAbleState.java
> +public interface ChangAbleState<T extends GameCharacter> {
changeable !!

2024-08-12 12:20 UTC, Irisation23 commented on irisation23/src/main/java/com/cowaine/irisation23/mission/game/domain/behavior/Attack.java
> +    }
<img width="799" alt="image" src="https://github.com/user-attachments/assets/f3da4e52-7a42-4d65-acfd-c77ce16ec3b3">

구조로 개선해 봤습니다~

2024-08-15 12:12 UTC, corock approved these changes

2024-09-19 01:56 UTC, merged